//------------------------------------------------------------------------------
// Copyright (c) 2015 Hewlett-Packard Development Company, L.P. and others.  All rights reserved.
// 
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v1.0 which accompanies this distribution,
// and is available at http://www.eclipse.org/legal/epl-v10.html
//------------------------------------------------------------------------------
package org.opendaylight.nic.extensibility;

import java.util.Set;

import org.opendaylight.nic.intent.AuxiliaryData;

/**
 * Handles translation of the given action type to the given native code.
 *
 * @param <N>
 *            native type that will be generated by translation
 * @author Shaun Wackerly
 */
public interface ActionTranslator<N> {

    /**
     * Translates the given action to a set of native actions.
     *
     * @param aux
     *            auxiliary data to help with translation
     * @return a set of native objects
     */
    Set<N> translate(AuxiliaryData aux);

    /**
     * The action label for which this is an acceptable translator.
     *
     * @return action label
     */
    ActionLabel actionLabel();

}
