//------------------------------------------------------------------------------
// Copyright (c) 2015 Hewlett-Packard Development Company, L.P. and others.  All rights reserved.
// 
// This program and the accompanying materials are made available under the
// terms of the Eclipse Public License v1.0 which accompanies this distribution,
// and is available at http://www.eclipse.org/legal/epl-v10.html
//------------------------------------------------------------------------------
package org.opendaylight.nic.extensibility;

import java.util.List;

import org.opendaylight.nic.intent.Interval;


/**
 * Handles translation of the given term type to the given type of code.
 *
 * @param <N> native builder that will be used for translation
 * @author Shaun Wackerly
 */
public interface TermTranslator<N> {

    /**
     * Translates the given term to the given native builder.
     *
     * @param builder the native builder
     * @param intervals list of intervals to be translated
     * @return a set of native objects
     */
    void translate(N builder, List<? extends Interval> intervals);

    /**
     * The term label for which this is an acceptable translator.
     *
     * @return term label
     */
    TermLabel termLabel();

    /**
     * The type of native objects which will be generated by this translator.
     *
     * @return native type
     */
    //Class<N> output();

    /**
     * The type of auxiliary data which will be required by this translator.
     *
     * @return auxiliary data type
     */
    //Class<X> auxiliary();

}
