/*
 * Generated file
 *
 * Generated from: yang module name: policy-manager yang module local name: policy-manager-id
 * Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
 * Generated at: Mon Dec 08 14:03:29 PST 2014
 *
 * Do not modify this file unless it is present under src/main directory
 */
package org.opendaylight.controller.config.yang.config.policy_manager.impl;

public class PolicyManagerModuleFactory
        extends
        org.opendaylight.controller.config.yang.config.policy_manager.impl.AbstractPolicyManagerModuleFactory {

}
