/*
* Generated file
*
* Generated from: yang module name: policy-compiler yang module local name: policy-compiler-id
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Wed Dec 10 15:02:33 PST 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.policy_compiler.impl;
public class PolicyCompilerModuleFactory extends org.opendaylight.controller.config.yang.config.policy_compiler.impl.AbstractPolicyCompilerModuleFactory {

}
