/*
* Generated file
*
* Generated from: yang module name: nic-api yang module local name: nic-identity
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Feb 23 11:08:27 PST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.nic_api.impl;
public class NetworkIntentCompositionModuleFactory extends org.opendaylight.controller.config.yang.config.nic_api.impl.AbstractNetworkIntentCompositionModuleFactory {

}
